### ISSUE TITLE
bibiを配置してepubを参照する際に404エラーになる

### ISSUE THREAD

**Issue by rmaimen** [sorshi/comistream-reader#2]
# ComiSteamをDockerで起動しbibiを設置したが、404エラーとなる

## 構築環境
* Windows11 Pro
* Docker

### docker command
```sh
docker run -d -p 8080:80 -v "C:/comistream/data:/home/user/comistream/data" -v "C:/comistream/public:/home/user/public" -v "C:/comistream/public/nas:/home/user/public/nas:ro" --restart unless-stopped --name comistream ghcr.io/sorshi/comistream-reader/comistream-reader:latest
```

### config
基本既定値のままです。
|設定項目|値|
|-|-|
|webRoot:|/home/user/public|
|publicDir:|/nas|
|sharePath:|/home/user/public/nas|
|bibiPath:|/bibi/|

### bibiの配置
```txt
C:\comistream\public\bibi
```

### epubの配置
```txt
C:\comistream\public\nas\test.epub
```

### Edgeで当該ファイルにアクセスした際のURL
```txt
http://localhost:8080/bibi/?book=/test.epub
```

## 原因予測
epubアクセス時のURL変換(？)で先頭の'/'が不要ではないかと思うのですが、
どこかで、設定できますか？

**Comment by sorshi** [comment]
ご連絡ありがとうございます。
ちょっと調べてみたところ、Bibiには
`http://localhost:8080/bibi/?book=/test.epub`
ではなく
`http://localhost:8080/bibi/?book=/nas/test.epub`
で渡さなければならない感じがしてきました。

よく考えれば当たり前感あるのですが、ベースになっている手元環境では/nasの階層がなく/public/Comic/のような構成で利用していたのでまったく気が付きませんでした。

Bibiに渡すときにはフルパスになるように対策考えていこうと思います。

**Comment by sorshi** [comment]
https://github.com/sorshi/comistream-reader/blob/0ded4f447a0adf21ada4ca99b7c84600dfa20268/comistream/theme/footer.html#L114 ここ修正すれば行けそうなんですけど、ちょっと動作確認する時間がいまないでございます…

**Comment by rmaimen** [comment]
早速の返信ありがとうございます。
最初の原因予測が間違っていました。すみません。

私の方も、ガサゴソやっていてきれいな環境で確認できておらず、
テストとしては足りていませんが、当該箇所を以下に書き換えて動かしたところたぶんうまく動きました。
```html
var openHref = bibiPath + "?book=" + publicDir + "/" + fileLink;
```

合わせて、bibiの機能に下記の物がありますが、
> ```EPUB ファイルをそのままアップロードして Bibi で開くと、動作が低速になる場合があります。そのときは、EPUB にする前のフォルダ、または EPUB を ZIP 展開してできるフォルダをアップロードし、 http://your.web.site/somewhere/bibi/?book=フォルダ名 にアクセスしてみてください。```
[Bibi 設置マニュアル](https://bibi.epub.link/manual.html#section-03)

に対応することは可能でしょうか？
こちらは全くの未確認でコメントしているので、すでに動くようなら申し訳ありません。

たぶん、拡張子で判断していると思うので、
.epubとついているディレクトリの場合は、/bibi/に.epubをのけて送るとかでできないかな？
と、適当に考えていました。ちょっと私も自由時間がなくて手を付けれていません。

**Comment by sorshi** [comment]
ご確認ありがとうございます。
Bibiは動作が、epub全体をクライアントに転送してからクライアントで展開する、という仕組みなため、大きいファイルになればなるほどComistream Readerのようにサーバーで展開してページだけ送ってくる方式と比べて出画に時間がかかるようになります。
いまのところepubはファイルサイズが小さいことが多いし全部送りつけてもまあ困らないかな、という妥協点でこうなっています。
あらかじめ展開しておく方式を利用するとなると、通常のコンテンツが入ってるディレクトリなのかepubを展開したディレクトリなのか区別が出来ないといけないんで、いまのところすぐには出来なさそうです。

**Comment by rmaimen** [comment]
わかりました。ありがとうございました。
